export const dashboardCopyScript = `
const copy = {
  title: 'FLOW Control Plane',
  subtitle: 'Задачи, запуски, артефакты и журналы текущего контура.',
  heroTitle: 'Состояние контура',
  heroSubtitle: 'Наблюдение за задачами, подтверждениями и результатами выполнения.',
  createTask: 'Новая задача',
  goalLabel: 'Задача',
  goalPlaceholder: 'Например: проверить состояние контура и подготовить следующий безопасный шаг',
  targetLabel: 'Контур',
  createButton: 'Создать задачу',
  stopTask: 'Остановить задачу',
  stopAllTasks: 'Остановить все задачи',
  stopRequested: 'Остановка запрошена',
  deleteRequested: 'Удаление запрошено',
  deleteTask: 'Удалить задачу',
  deleteAllTasks: 'Удалить все задачи',
  confirmationLabel: 'Подтверждение действия',
  confirmAction: 'Подтвердить',
  cancelAction: 'Отмена',
  stopTaskTitle: 'Остановить задачу',
  stopTaskConfirm: 'Выполнение будет остановлено после ближайшей безопасной точки.',
  stopAllTasksTitle: 'Остановить все задачи',
  stopAllTasksConfirm: 'Все активные задачи будут остановлены после ближайших безопасных точек.',
  deleteTaskTitle: 'Удалить задачу',
  deleteTaskConfirm: 'Задача и связанные с ней запуски, шаги, артефакты и служебные записи будут удалены. Действие необратимо.',
  deleteAllTasksTitle: 'Удалить все задачи',
  deleteAllTasksConfirm: 'Все задачи и связанные с ними данные будут удалены. Для активных задач сначала будет выполнена корректная остановка.',
  refreshButton: 'Обновить',
  approvals: 'Подтверждения',
  tasks: 'Задачи',
  runtime: 'Runtime',
  selectedTask: 'Выбранная задача',
  noTaskSelected: 'Выберите задачу, чтобы открыть детали выполнения.',
  maintenance: 'Обслуживание',
  targets: 'Контуры',
  schedules: 'Расписания',
  loading: 'Обновляю состояние FLOW...',
  viewOverview: 'Обзор',
  viewArtifacts: 'Артефакты',
  viewLogs: 'Журналы',
  viewRun: 'Запуск',
  pausePolling: 'Приостановить обновление',
  resumePolling: 'Возобновить обновление',
  enableCompact: 'Компактный режим',
  disableCompact: 'Стандартный режим',
  artifactRunFilter: 'Запуск',
  artifactTypeFilter: 'Тип артефакта',
  allRuns: 'Все запуски',
  allArtifactTypes: 'Все типы',
  noArtifacts: 'Для выбранной задачи артефактов пока нет.',
  noLogs: 'Операционные события пока не записаны.',
  runtimeLogLabel: 'Операционный журнал',
  runtimeLogTitle: 'Состояние журнала',
  runtimeLogSubtitle: 'Сводка по операционным событиям текущего контура.',
  runtimeLogFeedLabel: 'События',
  runtimeLogFeedTitle: 'Последние записи',
  runtimeLogFeedLimit: 'Показано последних записей: {count}',
  logTotalEntries: 'всего записей',
  logInfoEntries: 'info',
  logWarningEntries: 'warning',
  logErrorEntries: 'error',
  logLastEntryAt: 'последняя запись',
  rawDetails: 'Показать технические детали',
  hiddenNoise: 'Технические payload доступны по запросу.',
  dashboardReady: 'Панель управления готова.',
  streamConnected: 'Поток обновлений подключён',
  streamConnecting: 'Подключение к потоку обновлений…',
  streamPaused: 'Автообновление приостановлено',
  filterTasks: 'Состояние задачи',
  filterEvents: 'Уровень событий',
  filterApprovals: 'Статус подтверждения',
  allStates: 'Все состояния',
  allLevels: 'Все уровни',
  allApprovals: 'Все статусы',
  operatorActions: 'Действия оператора',
  attempt: 'Попытка',
  planPreview: 'План выполнения',
  criticFeedback: 'Замечания проверки плана',
  failureClasses: 'Классы отклонения',
  doNotRepeatRules: 'Правила повторного планирования',
  patchFiles: 'Файлы патча',
  patchHunks: 'Фрагменты',
  stateIdle: 'Нет активных задач',
};
`.trim();
