export const dashboardCopyScript = `
const copy = {
  title: 'FLOW Control Plane',
  subtitle: 'Управление задачами, подтверждениями, артефактами и журналами runtime.',
  createTask: 'Новая задача',
  goalLabel: 'Задача',
  targetLabel: 'Контур',
  createButton: 'Создать задачу',
  refreshButton: 'Обновить',
  approvals: 'Подтверждения',
  tasks: 'Задачи',
  runtime: 'Runtime',
  selectedTask: 'Выбранная задача',
  noTaskSelected: 'Выберите задачу, чтобы открыть детали выполнения.',
  maintenance: 'Обслуживание',
  targets: 'Контуры',
  schedules: 'Расписания',
  loading: 'Обновляю состояние FLOW...',
  viewOverview: 'Обзор',
  viewArtifacts: 'Артефакты',
  viewLogs: 'Журналы',
  viewRun: 'Запуск',
  pausePolling: 'Приостановить обновление',
  resumePolling: 'Возобновить обновление',
  enableCompact: 'Компактный режим',
  disableCompact: 'Стандартный режим',
  noArtifacts: 'Для выбранной задачи артефактов пока нет.',
  noLogs: 'Логи пока пусты.',
  rawDetails: 'Показать технические детали',
  hiddenNoise: 'Технические payload доступны по запросу.',
  dashboardReady: 'Панель управления готова.',
  streamConnected: 'Поток обновлений подключён',
  streamConnecting: 'Подключение к потоку обновлений…',
  streamPaused: 'Автообновление приостановлено',
  filterTasks: 'Состояние задачи',
  filterEvents: 'Уровень событий',
  filterApprovals: 'Статус подтверждения',
  allStates: 'Все состояния',
  allLevels: 'Все уровни',
  allApprovals: 'Все статусы',
  operatorActions: 'Действия оператора',
  patchFiles: 'Файлы патча',
  patchHunks: 'Фрагменты',
  stateIdle: 'Нет активных задач',
};
`.trim();
