export const dashboardCopyScript = `
const copy = {
  title: 'FLOW Control Plane',
  subtitle: 'Задачи, запуски, артефакты и журналы текущего контура.',
  heroTitle: 'Состояние контура',
  heroSubtitle: 'Наблюдение за задачами, подтверждениями и результатами выполнения.',
  createTask: 'Новая задача',
  goalLabel: 'Задача',
  targetLabel: 'Контур',
  createButton: 'Создать задачу',
  stopTask: 'Остановить задачу',
  stopAllTasks: 'Остановить все задачи',
  deleteTask: 'Удалить задачу',
  deleteAllTasks: 'Удалить все задачи',
  stopTaskConfirm: 'Остановить задачу после ближайшей безопасной точки выполнения?',
  stopAllTasksConfirm: 'Остановить все задачи после ближайших безопасных точек выполнения?',
  deleteTaskConfirm: 'Удалить задачу вместе с её запусками, шагами, артефактами и связанными записями? Действие необратимо.',
  deleteAllTasksConfirm: 'Удалить все задачи вместе с их запусками, шагами, артефактами и связанными записями? Действие необратимо.',
  refreshButton: 'Обновить',
  approvals: 'Подтверждения',
  tasks: 'Задачи',
  runtime: 'Runtime',
  selectedTask: 'Выбранная задача',
  noTaskSelected: 'Выберите задачу, чтобы открыть детали выполнения.',
  maintenance: 'Обслуживание',
  targets: 'Контуры',
  schedules: 'Расписания',
  loading: 'Обновляю состояние FLOW...',
  viewOverview: 'Обзор',
  viewArtifacts: 'Артефакты',
  viewLogs: 'Журналы',
  viewRun: 'Запуск',
  pausePolling: 'Приостановить обновление',
  resumePolling: 'Возобновить обновление',
  enableCompact: 'Компактный режим',
  disableCompact: 'Стандартный режим',
  artifactRunFilter: 'Запуск',
  artifactTypeFilter: 'Тип артефакта',
  allRuns: 'Все запуски',
  allArtifactTypes: 'Все типы',
  noArtifacts: 'Для выбранной задачи артефактов пока нет.',
  noLogs: 'Логи пока пусты.',
  rawDetails: 'Показать технические детали',
  hiddenNoise: 'Технические payload доступны по запросу.',
  dashboardReady: 'Панель управления готова.',
  streamConnected: 'Поток обновлений подключён',
  streamConnecting: 'Подключение к потоку обновлений…',
  streamPaused: 'Автообновление приостановлено',
  filterTasks: 'Состояние задачи',
  filterEvents: 'Уровень событий',
  filterApprovals: 'Статус подтверждения',
  allStates: 'Все состояния',
  allLevels: 'Все уровни',
  allApprovals: 'Все статусы',
  operatorActions: 'Действия оператора',
  attempt: 'Попытка',
  planPreview: 'План выполнения',
  criticFeedback: 'Замечания проверки плана',
  failureClasses: 'Классы отклонения',
  doNotRepeatRules: 'Правила повторного планирования',
  patchFiles: 'Файлы патча',
  patchHunks: 'Фрагменты',
  stateIdle: 'Нет активных задач',
};
`.trim();
